language: go

go:
  - 1.12.x

services:
  - redis-server
# Only clone the most recent commit.
git:
  depth: 1

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  global:
    - GO111MODULE=on
before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin

script:
  - go build ./...
  - go test ./...

after_success:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
